"""create review_topic and topic_names tables

Revision ID: 7b0bb08a9097
Revises: 7eaa5197780f
Create Date: 2026-07-20 11:02:34.301413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b0bb08a9097'
down_revision: Union[str, None] = '7eaa5197780f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_names',
    sa.Column('appid', sa.BigInteger(), nullable=False),
    sa.Column('topic_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('appid', 'topic_id')
    )
    op.create_table('review_topic',
    sa.Column('review_recommendation_id', sa.BigInteger(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['review_recommendation_id'], ['reviews.recommendation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_recommendation_id', 'topic_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_topic')
    op.drop_table('topic_names')
    # ### end Alembic commands ###
