"""create review_analysis table

Revision ID: 7eaa5197780f
Revises: e2903c8f92f8
Create Date: 2026-07-16 03:25:36.917190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eaa5197780f'
down_revision: Union[str, None] = 'e2903c8f92f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_analysis',
    sa.Column('review_recommendation_id', sa.BigInteger(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('sentiment_label', sa.String(length=16), nullable=False),
    sa.Column('matches_voted_up', sa.Boolean(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['review_recommendation_id'], ['reviews.recommendation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_recommendation_id')
    )
    op.create_index(op.f('ix_review_analysis_sentiment_label'), 'review_analysis', ['sentiment_label'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_analysis_sentiment_label'), table_name='review_analysis')
    op.drop_table('review_analysis')
    # ### end Alembic commands ###
