"""create reviews table

Revision ID: e2903c8f92f8
Revises: 
Create Date: 2026-07-15 03:37:25.168248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2903c8f92f8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('recommendation_id', sa.BigInteger(), nullable=False),
    sa.Column('appid', sa.BigInteger(), nullable=False),
    sa.Column('author_steamid', sa.String(length=32), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('voted_up', sa.Boolean(), nullable=False),
    sa.Column('playtime_at_review_min', sa.Integer(), nullable=False),
    sa.Column('votes_helpful', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recommendation_id')
    )
    op.create_index(op.f('ix_reviews_appid'), 'reviews', ['appid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_appid'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
